### ISSUE TITLE
Inconsistent annotation.name value on Google Chrome 51

### ISSUE THREAD

**Issue by fabo15x** [CocktailJS/cocktail#27]
On Google Chrome 51 an upwards 'annotation.name' returns 'ctor' which is inconsistent with the other browsers which return '@evented'. This prevents the registration of the event emitter from 'cocktail-annotation-evented'.

**Comment by elmasse** [comment]
@fabo15x: 

I tested **cocktail** v0.7.2 + cocktail-annotation-evented in Chrome 51 using TonicDev and it does work properly.

Chrome Version 51.0.2704.84 (64-bit)
See: https://tonicdev.com/5758c08f7c112613001e43bb/5758c08f7c112613001e43bc

Can you provide more information about this issue?

**Comment by elmasse** [comment]
My bad, I tested this bin on a Chrome v51 and bug is reproducible. 
--For the record TonicDev runs on NodeJS

http://jsbin.com/boxuba/edit

**Comment by elmasse** [comment]
Please test this version, I'll publish a new version once you confirm it is fixed.

**Comment by fabo15x** [comment]
@elmasse I will test it tomorrow morning. Thank you for your prompt response.

**Comment by fabo15x** [comment]
@elmasse I confirm it is fixed. Muchas gracias.
